logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # incoming HTTP request


google:
  map-key: AIzaSyC2CxkBl9JyAPvO0lAKDrvBHw4oURSCXFI

jwt:
  secret: "LaiTravel666"
  expirationHours: 3600